name: t_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter



  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2



  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.9

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/artgalleryicon.PNG
    - assets/icons/helpicon.PNG
    - assets/icons/howtoplayicon.PNG
    - assets/icons/libraryicon.PNG
    - assets/icons/carticon.PNG
    - assets/icons/participation.PNG
    - assets/icons/riseandshine.PNG
    - assets/icons/shellofsurvival.PNG
    - assets/icons/shieldofjustice.PNG
    - assets/getitrightlogofinal.PNG
    - assets/homepageheader.PNG
    - assets/icons/watchbutton.PNG
    - assets/icons/playbutton.PNG
    - assets/comic/comic1.jpg
    - assets/comic/comic2.jpg
    - assets/comic/comic3.jpg
    - assets/comic/comic4.jpg
    - assets/comic/comic5.jpg
    - assets/comic/comic6.jpg
    - assets/comic/comic7.jpg
    - assets/comic/comic8.jpg
    - assets/comic/comic9.jpg

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800